package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.Company;
import com.mutiny.demo.pojo.CompanyExample;
import java.util.List;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Company
     *
     * @mbg.generated 2020-04-27 19:06:07
     */
    int deleteByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Company
     *
     * @mbg.generated 2020-04-27 19:06:07
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Company
     *
     * @mbg.generated 2020-04-27 19:06:07
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Company
     *
     * @mbg.generated 2020-04-27 19:06:07
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Company
     *
     * @mbg.generated 2020-04-27 19:06:07
     */
    Company selectByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Company
     *
     * @mbg.generated 2020-04-27 19:06:07
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Company
     *
     * @mbg.generated 2020-04-27 19:06:07
     */
    int updateByPrimaryKey(Company record);
}