package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.FileOther;
import com.mutiny.demo.pojo.FileOtherExample;
import java.util.List;

public interface FileOtherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    int insert(FileOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    int insertSelective(FileOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    List<FileOther> selectByExample(FileOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    FileOther selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    int updateByPrimaryKeySelective(FileOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    int updateByPrimaryKey(FileOther record);
}