package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.FileModuleTemp;
import com.mutiny.demo.pojo.FileModuleTempExample;
import java.util.List;

public interface FileModuleTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    int insert(FileModuleTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    int insertSelective(FileModuleTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    List<FileModuleTemp> selectByExample(FileModuleTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    FileModuleTemp selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    int updateByPrimaryKeySelective(FileModuleTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    int updateByPrimaryKey(FileModuleTemp record);

    int GetSumByModuleId(int moduleId);

    int GetSumByDefaultModuleId(int moduleId);
}