package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.Govern;
import com.mutiny.demo.pojo.GovernExample;
import java.util.List;

public interface GovernMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    int deleteByPrimaryKey(Integer governid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    int insert(Govern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    int insertSelective(Govern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    List<Govern> selectByExample(GovernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    Govern selectByPrimaryKey(Integer governid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    int updateByPrimaryKeySelective(Govern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    int updateByPrimaryKey(Govern record);
}