package com.mutiny.demo.dao;

import com.mutiny.demo.dto.CalculateShowCalDTO;
import com.mutiny.demo.pojo.Log;
import com.mutiny.demo.pojo.LogExample;
import java.util.List;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated 2020-01-30 11:38:32
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated 2020-01-30 11:38:32
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated 2020-01-30 11:38:32
     */
    List<Log> selectByExample(LogExample example);
    List<CalculateShowCalDTO> showApiData();
}