package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.MessageInfo;
import com.mutiny.demo.pojo.MessageInfoExample;
import java.util.List;

public interface MessageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Info
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int deleteByPrimaryKey(Integer messageInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Info
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int insert(MessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Info
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int insertSelective(MessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Info
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    List<MessageInfo> selectByExample(MessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Info
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    MessageInfo selectByPrimaryKey(Integer messageInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Info
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int updateByPrimaryKeySelective(MessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Info
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int updateByPrimaryKey(MessageInfo record);
}