package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.MessageUser;
import com.mutiny.demo.pojo.MessageUserExample;
import java.util.List;

public interface MessageUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_User
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int deleteByPrimaryKey(Integer messageUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_User
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int insert(MessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_User
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int insertSelective(MessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_User
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    List<MessageUser> selectByExample(MessageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_User
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    MessageUser selectByPrimaryKey(Integer messageUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_User
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int updateByPrimaryKeySelective(MessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_User
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int updateByPrimaryKey(MessageUser record);
}