package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.MessageSend;
import com.mutiny.demo.pojo.MessageSendExample;
import java.util.List;

public interface MessageSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Send
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int deleteByPrimaryKey(Integer messageSendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Send
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int insert(MessageSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Send
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int insertSelective(MessageSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Send
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    List<MessageSend> selectByExample(MessageSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Send
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    MessageSend selectByPrimaryKey(Integer messageSendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Send
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int updateByPrimaryKeySelective(MessageSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message_Send
     *
     * @mbg.generated 2020-03-21 14:40:16
     */
    int updateByPrimaryKey(MessageSend record);
}