package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.Module;
import com.mutiny.demo.pojo.ModuleExample;
import java.util.List;

public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int deleteByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    List<Module> selectByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    Module selectByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int updateByPrimaryKey(Module record);
    int GetCount();
}