package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.ModuleUser;
import com.mutiny.demo.pojo.ModuleUserExample;
import java.util.List;

public interface ModuleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module_User
     *
     * @mbg.generated 2020-03-23 17:06:04
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module_User
     *
     * @mbg.generated 2020-03-23 17:06:04
     */
    int insert(ModuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module_User
     *
     * @mbg.generated 2020-03-23 17:06:04
     */
    int insertSelective(ModuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module_User
     *
     * @mbg.generated 2020-03-23 17:06:04
     */
    List<ModuleUser> selectByExample(ModuleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module_User
     *
     * @mbg.generated 2020-03-23 17:06:04
     */
    ModuleUser selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module_User
     *
     * @mbg.generated 2020-03-23 17:06:04
     */
    int updateByPrimaryKeySelective(ModuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module_User
     *
     * @mbg.generated 2020-03-23 17:06:04
     */
    int updateByPrimaryKey(ModuleUser record);

    String findCreater(int projectId);
}