package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.Project;
import com.mutiny.demo.pojo.ProjectExample;
import java.util.List;

public interface ProjectMapper {
    int GetIsEndCount(String username,String Type,Integer flag);
    List<Project> GetProjectList(String username,String Type,Integer Is_default,Integer currIndex,Integer pagesize);
    List<Project> GetProjectListAll(String username,String Type,Integer Is_default);
    int GetCount();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    int deleteByPrimaryKey(Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    Project selectByPrimaryKey(Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    int updateByPrimaryKey(Project record);
}