package com.mutiny.demo.dao;

import com.mutiny.demo.pojo.ProjectUser;
import com.mutiny.demo.pojo.ProjectUserExample;
import java.util.List;

public interface ProjectUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int insert(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int insertSelective(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    List<ProjectUser> selectByExample(ProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    ProjectUser selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int updateByPrimaryKeySelective(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    int updateByPrimaryKey(ProjectUser record);
    String findCreater(Integer projectId);
}