package com.mutiny.demo.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table File_Other
 *
 * @mbg.generated do_not_delete_during_merge 2020-02-06 12:44:57
 */
public class FileOther implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Other.File_ID
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Other.File_Name
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Other.File_URL
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    private String fileUrl;

    /**
     * Database Column Remarks:
     *   0头像，1许可证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Other.Type
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Other.File_ID
     *
     * @return the value of File_Other.File_ID
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Other.File_ID
     *
     * @param fileId the value for File_Other.File_ID
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Other.File_Name
     *
     * @return the value of File_Other.File_Name
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Other.File_Name
     *
     * @param fileName the value for File_Other.File_Name
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Other.File_URL
     *
     * @return the value of File_Other.File_URL
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Other.File_URL
     *
     * @param fileUrl the value for File_Other.File_URL
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Other.Type
     *
     * @return the value of File_Other.Type
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Other.Type
     *
     * @param type the value for File_Other.Type
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Other
     *
     * @mbg.generated 2020-02-06 12:44:57
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", fileName=").append(fileName);
        sb.append(", fileUrl=").append(fileUrl);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}