package com.mutiny.demo.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table File_Module_Temp
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-16 13:16:33
 */
public class FileModuleTemp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.File_ID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.File_Name
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.File_URL
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.Module_ID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private Integer moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.Uploader
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private String uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.Encode_Algorithm
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private String encodeAlgorithm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.TotleParam
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private Integer totleparam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.NowParam
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private Integer nowparam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.DefaultID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private Integer defaultid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.Is_Default
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private Boolean isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Module_Temp.KeyFileId
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private Integer keyfileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.File_ID
     *
     * @return the value of File_Module_Temp.File_ID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.File_ID
     *
     * @param fileId the value for File_Module_Temp.File_ID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.File_Name
     *
     * @return the value of File_Module_Temp.File_Name
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.File_Name
     *
     * @param fileName the value for File_Module_Temp.File_Name
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.File_URL
     *
     * @return the value of File_Module_Temp.File_URL
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.File_URL
     *
     * @param fileUrl the value for File_Module_Temp.File_URL
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.Module_ID
     *
     * @return the value of File_Module_Temp.Module_ID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.Module_ID
     *
     * @param moduleId the value for File_Module_Temp.Module_ID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.Uploader
     *
     * @return the value of File_Module_Temp.Uploader
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.Uploader
     *
     * @param uploader the value for File_Module_Temp.Uploader
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.Encode_Algorithm
     *
     * @return the value of File_Module_Temp.Encode_Algorithm
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public String getEncodeAlgorithm() {
        return encodeAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.Encode_Algorithm
     *
     * @param encodeAlgorithm the value for File_Module_Temp.Encode_Algorithm
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setEncodeAlgorithm(String encodeAlgorithm) {
        this.encodeAlgorithm = encodeAlgorithm == null ? null : encodeAlgorithm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.TotleParam
     *
     * @return the value of File_Module_Temp.TotleParam
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Integer getTotleparam() {
        return totleparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.TotleParam
     *
     * @param totleparam the value for File_Module_Temp.TotleParam
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setTotleparam(Integer totleparam) {
        this.totleparam = totleparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.NowParam
     *
     * @return the value of File_Module_Temp.NowParam
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Integer getNowparam() {
        return nowparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.NowParam
     *
     * @param nowparam the value for File_Module_Temp.NowParam
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setNowparam(Integer nowparam) {
        this.nowparam = nowparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.DefaultID
     *
     * @return the value of File_Module_Temp.DefaultID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Integer getDefaultid() {
        return defaultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.DefaultID
     *
     * @param defaultid the value for File_Module_Temp.DefaultID
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setDefaultid(Integer defaultid) {
        this.defaultid = defaultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.Is_Default
     *
     * @return the value of File_Module_Temp.Is_Default
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.Is_Default
     *
     * @param isDefault the value for File_Module_Temp.Is_Default
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Module_Temp.KeyFileId
     *
     * @return the value of File_Module_Temp.KeyFileId
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Integer getKeyfileid() {
        return keyfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Module_Temp.KeyFileId
     *
     * @param keyfileid the value for File_Module_Temp.KeyFileId
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setKeyfileid(Integer keyfileid) {
        this.keyfileid = keyfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", fileName=").append(fileName);
        sb.append(", fileUrl=").append(fileUrl);
        sb.append(", moduleId=").append(moduleId);
        sb.append(", uploader=").append(uploader);
        sb.append(", encodeAlgorithm=").append(encodeAlgorithm);
        sb.append(", totleparam=").append(totleparam);
        sb.append(", nowparam=").append(nowparam);
        sb.append(", defaultid=").append(defaultid);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", keyfileid=").append(keyfileid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}