package com.mutiny.demo.pojo;

import java.util.ArrayList;
import java.util.List;

public class FileModuleTempExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public FileModuleTempExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileIdIsNull() {
            addCriterion("File_ID is null");
            return (Criteria) this;
        }

        public Criteria andFileIdIsNotNull() {
            addCriterion("File_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFileIdEqualTo(Integer value) {
            addCriterion("File_ID =", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotEqualTo(Integer value) {
            addCriterion("File_ID <>", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThan(Integer value) {
            addCriterion("File_ID >", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("File_ID >=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThan(Integer value) {
            addCriterion("File_ID <", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("File_ID <=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdIn(List<Integer> values) {
            addCriterion("File_ID in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotIn(List<Integer> values) {
            addCriterion("File_ID not in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdBetween(Integer value1, Integer value2) {
            addCriterion("File_ID between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("File_ID not between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("File_Name is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("File_Name is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("File_Name =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("File_Name <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("File_Name >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("File_Name >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("File_Name <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("File_Name <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("File_Name like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("File_Name not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("File_Name in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("File_Name not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("File_Name between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("File_Name not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileUrlIsNull() {
            addCriterion("File_URL is null");
            return (Criteria) this;
        }

        public Criteria andFileUrlIsNotNull() {
            addCriterion("File_URL is not null");
            return (Criteria) this;
        }

        public Criteria andFileUrlEqualTo(String value) {
            addCriterion("File_URL =", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlNotEqualTo(String value) {
            addCriterion("File_URL <>", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlGreaterThan(String value) {
            addCriterion("File_URL >", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlGreaterThanOrEqualTo(String value) {
            addCriterion("File_URL >=", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlLessThan(String value) {
            addCriterion("File_URL <", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlLessThanOrEqualTo(String value) {
            addCriterion("File_URL <=", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlLike(String value) {
            addCriterion("File_URL like", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlNotLike(String value) {
            addCriterion("File_URL not like", value, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlIn(List<String> values) {
            addCriterion("File_URL in", values, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlNotIn(List<String> values) {
            addCriterion("File_URL not in", values, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlBetween(String value1, String value2) {
            addCriterion("File_URL between", value1, value2, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andFileUrlNotBetween(String value1, String value2) {
            addCriterion("File_URL not between", value1, value2, "fileUrl");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNull() {
            addCriterion("Module_ID is null");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNotNull() {
            addCriterion("Module_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModuleIdEqualTo(Integer value) {
            addCriterion("Module_ID =", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotEqualTo(Integer value) {
            addCriterion("Module_ID <>", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThan(Integer value) {
            addCriterion("Module_ID >", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Module_ID >=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThan(Integer value) {
            addCriterion("Module_ID <", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThanOrEqualTo(Integer value) {
            addCriterion("Module_ID <=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdIn(List<Integer> values) {
            addCriterion("Module_ID in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotIn(List<Integer> values) {
            addCriterion("Module_ID not in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdBetween(Integer value1, Integer value2) {
            addCriterion("Module_ID between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Module_ID not between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNull() {
            addCriterion("Uploader is null");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNotNull() {
            addCriterion("Uploader is not null");
            return (Criteria) this;
        }

        public Criteria andUploaderEqualTo(String value) {
            addCriterion("Uploader =", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotEqualTo(String value) {
            addCriterion("Uploader <>", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThan(String value) {
            addCriterion("Uploader >", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThanOrEqualTo(String value) {
            addCriterion("Uploader >=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThan(String value) {
            addCriterion("Uploader <", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThanOrEqualTo(String value) {
            addCriterion("Uploader <=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLike(String value) {
            addCriterion("Uploader like", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotLike(String value) {
            addCriterion("Uploader not like", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderIn(List<String> values) {
            addCriterion("Uploader in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotIn(List<String> values) {
            addCriterion("Uploader not in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderBetween(String value1, String value2) {
            addCriterion("Uploader between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotBetween(String value1, String value2) {
            addCriterion("Uploader not between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmIsNull() {
            addCriterion("Encode_Algorithm is null");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmIsNotNull() {
            addCriterion("Encode_Algorithm is not null");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmEqualTo(String value) {
            addCriterion("Encode_Algorithm =", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmNotEqualTo(String value) {
            addCriterion("Encode_Algorithm <>", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmGreaterThan(String value) {
            addCriterion("Encode_Algorithm >", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmGreaterThanOrEqualTo(String value) {
            addCriterion("Encode_Algorithm >=", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmLessThan(String value) {
            addCriterion("Encode_Algorithm <", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmLessThanOrEqualTo(String value) {
            addCriterion("Encode_Algorithm <=", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmLike(String value) {
            addCriterion("Encode_Algorithm like", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmNotLike(String value) {
            addCriterion("Encode_Algorithm not like", value, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmIn(List<String> values) {
            addCriterion("Encode_Algorithm in", values, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmNotIn(List<String> values) {
            addCriterion("Encode_Algorithm not in", values, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmBetween(String value1, String value2) {
            addCriterion("Encode_Algorithm between", value1, value2, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andEncodeAlgorithmNotBetween(String value1, String value2) {
            addCriterion("Encode_Algorithm not between", value1, value2, "encodeAlgorithm");
            return (Criteria) this;
        }

        public Criteria andTotleparamIsNull() {
            addCriterion("TotleParam is null");
            return (Criteria) this;
        }

        public Criteria andTotleparamIsNotNull() {
            addCriterion("TotleParam is not null");
            return (Criteria) this;
        }

        public Criteria andTotleparamEqualTo(Integer value) {
            addCriterion("TotleParam =", value, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamNotEqualTo(Integer value) {
            addCriterion("TotleParam <>", value, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamGreaterThan(Integer value) {
            addCriterion("TotleParam >", value, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamGreaterThanOrEqualTo(Integer value) {
            addCriterion("TotleParam >=", value, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamLessThan(Integer value) {
            addCriterion("TotleParam <", value, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamLessThanOrEqualTo(Integer value) {
            addCriterion("TotleParam <=", value, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamIn(List<Integer> values) {
            addCriterion("TotleParam in", values, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamNotIn(List<Integer> values) {
            addCriterion("TotleParam not in", values, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamBetween(Integer value1, Integer value2) {
            addCriterion("TotleParam between", value1, value2, "totleparam");
            return (Criteria) this;
        }

        public Criteria andTotleparamNotBetween(Integer value1, Integer value2) {
            addCriterion("TotleParam not between", value1, value2, "totleparam");
            return (Criteria) this;
        }

        public Criteria andNowparamIsNull() {
            addCriterion("NowParam is null");
            return (Criteria) this;
        }

        public Criteria andNowparamIsNotNull() {
            addCriterion("NowParam is not null");
            return (Criteria) this;
        }

        public Criteria andNowparamEqualTo(Integer value) {
            addCriterion("NowParam =", value, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamNotEqualTo(Integer value) {
            addCriterion("NowParam <>", value, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamGreaterThan(Integer value) {
            addCriterion("NowParam >", value, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamGreaterThanOrEqualTo(Integer value) {
            addCriterion("NowParam >=", value, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamLessThan(Integer value) {
            addCriterion("NowParam <", value, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamLessThanOrEqualTo(Integer value) {
            addCriterion("NowParam <=", value, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamIn(List<Integer> values) {
            addCriterion("NowParam in", values, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamNotIn(List<Integer> values) {
            addCriterion("NowParam not in", values, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamBetween(Integer value1, Integer value2) {
            addCriterion("NowParam between", value1, value2, "nowparam");
            return (Criteria) this;
        }

        public Criteria andNowparamNotBetween(Integer value1, Integer value2) {
            addCriterion("NowParam not between", value1, value2, "nowparam");
            return (Criteria) this;
        }

        public Criteria andDefaultidIsNull() {
            addCriterion("DefaultID is null");
            return (Criteria) this;
        }

        public Criteria andDefaultidIsNotNull() {
            addCriterion("DefaultID is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultidEqualTo(Integer value) {
            addCriterion("DefaultID =", value, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidNotEqualTo(Integer value) {
            addCriterion("DefaultID <>", value, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidGreaterThan(Integer value) {
            addCriterion("DefaultID >", value, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidGreaterThanOrEqualTo(Integer value) {
            addCriterion("DefaultID >=", value, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidLessThan(Integer value) {
            addCriterion("DefaultID <", value, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidLessThanOrEqualTo(Integer value) {
            addCriterion("DefaultID <=", value, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidIn(List<Integer> values) {
            addCriterion("DefaultID in", values, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidNotIn(List<Integer> values) {
            addCriterion("DefaultID not in", values, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidBetween(Integer value1, Integer value2) {
            addCriterion("DefaultID between", value1, value2, "defaultid");
            return (Criteria) this;
        }

        public Criteria andDefaultidNotBetween(Integer value1, Integer value2) {
            addCriterion("DefaultID not between", value1, value2, "defaultid");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNull() {
            addCriterion("Is_Default is null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNotNull() {
            addCriterion("Is_Default is not null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultEqualTo(Boolean value) {
            addCriterion("Is_Default =", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotEqualTo(Boolean value) {
            addCriterion("Is_Default <>", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThan(Boolean value) {
            addCriterion("Is_Default >", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThanOrEqualTo(Boolean value) {
            addCriterion("Is_Default >=", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThan(Boolean value) {
            addCriterion("Is_Default <", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThanOrEqualTo(Boolean value) {
            addCriterion("Is_Default <=", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIn(List<Boolean> values) {
            addCriterion("Is_Default in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotIn(List<Boolean> values) {
            addCriterion("Is_Default not in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_Default between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_Default not between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andKeyfileidIsNull() {
            addCriterion("KeyFileId is null");
            return (Criteria) this;
        }

        public Criteria andKeyfileidIsNotNull() {
            addCriterion("KeyFileId is not null");
            return (Criteria) this;
        }

        public Criteria andKeyfileidEqualTo(Integer value) {
            addCriterion("KeyFileId =", value, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidNotEqualTo(Integer value) {
            addCriterion("KeyFileId <>", value, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidGreaterThan(Integer value) {
            addCriterion("KeyFileId >", value, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidGreaterThanOrEqualTo(Integer value) {
            addCriterion("KeyFileId >=", value, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidLessThan(Integer value) {
            addCriterion("KeyFileId <", value, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidLessThanOrEqualTo(Integer value) {
            addCriterion("KeyFileId <=", value, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidIn(List<Integer> values) {
            addCriterion("KeyFileId in", values, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidNotIn(List<Integer> values) {
            addCriterion("KeyFileId not in", values, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidBetween(Integer value1, Integer value2) {
            addCriterion("KeyFileId between", value1, value2, "keyfileid");
            return (Criteria) this;
        }

        public Criteria andKeyfileidNotBetween(Integer value1, Integer value2) {
            addCriterion("KeyFileId not between", value1, value2, "keyfileid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table File_Module_Temp
     *
     * @mbg.generated do_not_delete_during_merge 2020-03-16 13:16:33
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table File_Module_Temp
     *
     * @mbg.generated 2020-03-16 13:16:33
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}