package com.mutiny.demo.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Govern
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-20 13:22:20
 */
public class Govern implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Govern.GovernId
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    private Integer governid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Govern.Name
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    private String name;

    /**
     * Database Column Remarks:
     *   文件ID[企业为营业执照|政府为组织机构代码证]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Govern.FileId
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    private Integer fileid;

    /**
     * Database Column Remarks:
     *   认证code[企业为社会统一信用代码|政府为组织机构代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Govern.Cer_Code
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    private String cerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Govern.GovernId
     *
     * @return the value of Govern.GovernId
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public Integer getGovernid() {
        return governid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Govern.GovernId
     *
     * @param governid the value for Govern.GovernId
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public void setGovernid(Integer governid) {
        this.governid = governid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Govern.Name
     *
     * @return the value of Govern.Name
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Govern.Name
     *
     * @param name the value for Govern.Name
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Govern.FileId
     *
     * @return the value of Govern.FileId
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Govern.FileId
     *
     * @param fileid the value for Govern.FileId
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Govern.Cer_Code
     *
     * @return the value of Govern.Cer_Code
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public String getCerCode() {
        return cerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Govern.Cer_Code
     *
     * @param cerCode the value for Govern.Cer_Code
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    public void setCerCode(String cerCode) {
        this.cerCode = cerCode == null ? null : cerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Govern
     *
     * @mbg.generated 2020-03-20 13:22:20
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", governid=").append(governid);
        sb.append(", name=").append(name);
        sb.append(", fileid=").append(fileid);
        sb.append(", cerCode=").append(cerCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}