package com.mutiny.demo.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Project_User
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-30 21:05:22
 */
public class ProjectUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project_User.Relation_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    private Integer relationId;

    /**
     * Database Column Remarks:
     *   外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project_User.Project_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    private Integer projectId;

    /**
     * Database Column Remarks:
     *   外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project_User.User_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project_User.Type
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project_User.inTime
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    private Date intime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project_User.Relation_ID
     *
     * @return the value of Project_User.Relation_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project_User.Relation_ID
     *
     * @param relationId the value for Project_User.Relation_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project_User.Project_ID
     *
     * @return the value of Project_User.Project_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project_User.Project_ID
     *
     * @param projectId the value for Project_User.Project_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project_User.User_ID
     *
     * @return the value of Project_User.User_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project_User.User_ID
     *
     * @param userId the value for Project_User.User_ID
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project_User.Type
     *
     * @return the value of Project_User.Type
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project_User.Type
     *
     * @param type the value for Project_User.Type
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project_User.inTime
     *
     * @return the value of Project_User.inTime
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project_User.inTime
     *
     * @param intime the value for Project_User.inTime
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project_User
     *
     * @mbg.generated 2020-03-30 21:05:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", relationId=").append(relationId);
        sb.append(", projectId=").append(projectId);
        sb.append(", userId=").append(userId);
        sb.append(", type=").append(type);
        sb.append(", intime=").append(intime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}