package com.mutiny.demo.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Project
 *
 * @mbg.generated do_not_delete_during_merge 2020-01-16 18:43:07
 */
public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Project_ID
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Project_Name
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private String projectName;

    /**
     * Database Column Remarks:
     *   项目用途
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Project_Purpose
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private String projectPurpose;

    /**
     * Database Column Remarks:
     *   项目描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Project_Description
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private String projectDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Create_Time
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   模型描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Module_Description
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private String moduleDescription;

    /**
     * Database Column Remarks:
     *   一级邀请码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Invite_Code_1
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private String inviteCode1;

    /**
     * Database Column Remarks:
     *   二级邀请码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Invite_Code_2
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private String inviteCode2;

    /**
     * Database Column Remarks:
     *   是否固定模型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Is_Default
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private Boolean isDefault;

    /**
     * Database Column Remarks:
     *   是否计算结束
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Is_End
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private Boolean isEnd;

    /**
     * Database Column Remarks:
     *   是否删除（弃用）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.Is_Userful
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private Boolean isUserful;

    /**
     * Database Column Remarks:
     *   1基本信息2输入风控模型3邀请他人及信息4开始计算5计算结束
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.stage
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private Integer stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Project_ID
     *
     * @return the value of Project.Project_ID
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Project_ID
     *
     * @param projectId the value for Project.Project_ID
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Project_Name
     *
     * @return the value of Project.Project_Name
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Project_Name
     *
     * @param projectName the value for Project.Project_Name
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Project_Purpose
     *
     * @return the value of Project.Project_Purpose
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public String getProjectPurpose() {
        return projectPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Project_Purpose
     *
     * @param projectPurpose the value for Project.Project_Purpose
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setProjectPurpose(String projectPurpose) {
        this.projectPurpose = projectPurpose == null ? null : projectPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Project_Description
     *
     * @return the value of Project.Project_Description
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Project_Description
     *
     * @param projectDescription the value for Project.Project_Description
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription == null ? null : projectDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Create_Time
     *
     * @return the value of Project.Create_Time
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Create_Time
     *
     * @param createTime the value for Project.Create_Time
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Module_Description
     *
     * @return the value of Project.Module_Description
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public String getModuleDescription() {
        return moduleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Module_Description
     *
     * @param moduleDescription the value for Project.Module_Description
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setModuleDescription(String moduleDescription) {
        this.moduleDescription = moduleDescription == null ? null : moduleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Invite_Code_1
     *
     * @return the value of Project.Invite_Code_1
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public String getInviteCode1() {
        return inviteCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Invite_Code_1
     *
     * @param inviteCode1 the value for Project.Invite_Code_1
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setInviteCode1(String inviteCode1) {
        this.inviteCode1 = inviteCode1 == null ? null : inviteCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Invite_Code_2
     *
     * @return the value of Project.Invite_Code_2
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public String getInviteCode2() {
        return inviteCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Invite_Code_2
     *
     * @param inviteCode2 the value for Project.Invite_Code_2
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setInviteCode2(String inviteCode2) {
        this.inviteCode2 = inviteCode2 == null ? null : inviteCode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Is_Default
     *
     * @return the value of Project.Is_Default
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Is_Default
     *
     * @param isDefault the value for Project.Is_Default
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Is_End
     *
     * @return the value of Project.Is_End
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Boolean getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Is_End
     *
     * @param isEnd the value for Project.Is_End
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setIsEnd(Boolean isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.Is_Userful
     *
     * @return the value of Project.Is_Userful
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Boolean getIsUserful() {
        return isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.Is_Userful
     *
     * @param isUserful the value for Project.Is_Userful
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setIsUserful(Boolean isUserful) {
        this.isUserful = isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.stage
     *
     * @return the value of Project.stage
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Integer getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.stage
     *
     * @param stage the value for Project.stage
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setStage(Integer stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectId=").append(projectId);
        sb.append(", projectName=").append(projectName);
        sb.append(", projectPurpose=").append(projectPurpose);
        sb.append(", projectDescription=").append(projectDescription);
        sb.append(", createTime=").append(createTime);
        sb.append(", moduleDescription=").append(moduleDescription);
        sb.append(", inviteCode1=").append(inviteCode1);
        sb.append(", inviteCode2=").append(inviteCode2);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", isEnd=").append(isEnd);
        sb.append(", isUserful=").append(isUserful);
        sb.append(", stage=").append(stage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}