package com.mutiny.demo.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("Project_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("Project_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("Project_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("Project_ID <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("Project_ID >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Project_ID >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("Project_ID <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("Project_ID <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("Project_ID in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("Project_ID not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("Project_ID between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Project_ID not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("Project_Name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("Project_Name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("Project_Name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("Project_Name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("Project_Name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("Project_Name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("Project_Name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("Project_Name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("Project_Name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("Project_Name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("Project_Name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("Project_Name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("Project_Name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("Project_Name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeIsNull() {
            addCriterion("Project_Purpose is null");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeIsNotNull() {
            addCriterion("Project_Purpose is not null");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeEqualTo(String value) {
            addCriterion("Project_Purpose =", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeNotEqualTo(String value) {
            addCriterion("Project_Purpose <>", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeGreaterThan(String value) {
            addCriterion("Project_Purpose >", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeGreaterThanOrEqualTo(String value) {
            addCriterion("Project_Purpose >=", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeLessThan(String value) {
            addCriterion("Project_Purpose <", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeLessThanOrEqualTo(String value) {
            addCriterion("Project_Purpose <=", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeLike(String value) {
            addCriterion("Project_Purpose like", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeNotLike(String value) {
            addCriterion("Project_Purpose not like", value, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeIn(List<String> values) {
            addCriterion("Project_Purpose in", values, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeNotIn(List<String> values) {
            addCriterion("Project_Purpose not in", values, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeBetween(String value1, String value2) {
            addCriterion("Project_Purpose between", value1, value2, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectPurposeNotBetween(String value1, String value2) {
            addCriterion("Project_Purpose not between", value1, value2, "projectPurpose");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionIsNull() {
            addCriterion("Project_Description is null");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionIsNotNull() {
            addCriterion("Project_Description is not null");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionEqualTo(String value) {
            addCriterion("Project_Description =", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionNotEqualTo(String value) {
            addCriterion("Project_Description <>", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionGreaterThan(String value) {
            addCriterion("Project_Description >", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Project_Description >=", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionLessThan(String value) {
            addCriterion("Project_Description <", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Project_Description <=", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionLike(String value) {
            addCriterion("Project_Description like", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionNotLike(String value) {
            addCriterion("Project_Description not like", value, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionIn(List<String> values) {
            addCriterion("Project_Description in", values, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionNotIn(List<String> values) {
            addCriterion("Project_Description not in", values, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionBetween(String value1, String value2) {
            addCriterion("Project_Description between", value1, value2, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andProjectDescriptionNotBetween(String value1, String value2) {
            addCriterion("Project_Description not between", value1, value2, "projectDescription");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("Create_Time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("Create_Time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("Create_Time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("Create_Time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("Create_Time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("Create_Time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Create_Time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("Create_Time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("Create_Time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("Create_Time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Create_Time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionIsNull() {
            addCriterion("Module_Description is null");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionIsNotNull() {
            addCriterion("Module_Description is not null");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionEqualTo(String value) {
            addCriterion("Module_Description =", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionNotEqualTo(String value) {
            addCriterion("Module_Description <>", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionGreaterThan(String value) {
            addCriterion("Module_Description >", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Module_Description >=", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionLessThan(String value) {
            addCriterion("Module_Description <", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Module_Description <=", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionLike(String value) {
            addCriterion("Module_Description like", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionNotLike(String value) {
            addCriterion("Module_Description not like", value, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionIn(List<String> values) {
            addCriterion("Module_Description in", values, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionNotIn(List<String> values) {
            addCriterion("Module_Description not in", values, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionBetween(String value1, String value2) {
            addCriterion("Module_Description between", value1, value2, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andModuleDescriptionNotBetween(String value1, String value2) {
            addCriterion("Module_Description not between", value1, value2, "moduleDescription");
            return (Criteria) this;
        }

        public Criteria andInviteCode1IsNull() {
            addCriterion("Invite_Code_1 is null");
            return (Criteria) this;
        }

        public Criteria andInviteCode1IsNotNull() {
            addCriterion("Invite_Code_1 is not null");
            return (Criteria) this;
        }

        public Criteria andInviteCode1EqualTo(String value) {
            addCriterion("Invite_Code_1 =", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1NotEqualTo(String value) {
            addCriterion("Invite_Code_1 <>", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1GreaterThan(String value) {
            addCriterion("Invite_Code_1 >", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1GreaterThanOrEqualTo(String value) {
            addCriterion("Invite_Code_1 >=", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1LessThan(String value) {
            addCriterion("Invite_Code_1 <", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1LessThanOrEqualTo(String value) {
            addCriterion("Invite_Code_1 <=", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1Like(String value) {
            addCriterion("Invite_Code_1 like", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1NotLike(String value) {
            addCriterion("Invite_Code_1 not like", value, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1In(List<String> values) {
            addCriterion("Invite_Code_1 in", values, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1NotIn(List<String> values) {
            addCriterion("Invite_Code_1 not in", values, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1Between(String value1, String value2) {
            addCriterion("Invite_Code_1 between", value1, value2, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode1NotBetween(String value1, String value2) {
            addCriterion("Invite_Code_1 not between", value1, value2, "inviteCode1");
            return (Criteria) this;
        }

        public Criteria andInviteCode2IsNull() {
            addCriterion("Invite_Code_2 is null");
            return (Criteria) this;
        }

        public Criteria andInviteCode2IsNotNull() {
            addCriterion("Invite_Code_2 is not null");
            return (Criteria) this;
        }

        public Criteria andInviteCode2EqualTo(String value) {
            addCriterion("Invite_Code_2 =", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2NotEqualTo(String value) {
            addCriterion("Invite_Code_2 <>", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2GreaterThan(String value) {
            addCriterion("Invite_Code_2 >", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2GreaterThanOrEqualTo(String value) {
            addCriterion("Invite_Code_2 >=", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2LessThan(String value) {
            addCriterion("Invite_Code_2 <", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2LessThanOrEqualTo(String value) {
            addCriterion("Invite_Code_2 <=", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2Like(String value) {
            addCriterion("Invite_Code_2 like", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2NotLike(String value) {
            addCriterion("Invite_Code_2 not like", value, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2In(List<String> values) {
            addCriterion("Invite_Code_2 in", values, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2NotIn(List<String> values) {
            addCriterion("Invite_Code_2 not in", values, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2Between(String value1, String value2) {
            addCriterion("Invite_Code_2 between", value1, value2, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andInviteCode2NotBetween(String value1, String value2) {
            addCriterion("Invite_Code_2 not between", value1, value2, "inviteCode2");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNull() {
            addCriterion("Is_Default is null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNotNull() {
            addCriterion("Is_Default is not null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultEqualTo(Boolean value) {
            addCriterion("Is_Default =", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotEqualTo(Boolean value) {
            addCriterion("Is_Default <>", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThan(Boolean value) {
            addCriterion("Is_Default >", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThanOrEqualTo(Boolean value) {
            addCriterion("Is_Default >=", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThan(Boolean value) {
            addCriterion("Is_Default <", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThanOrEqualTo(Boolean value) {
            addCriterion("Is_Default <=", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIn(List<Boolean> values) {
            addCriterion("Is_Default in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotIn(List<Boolean> values) {
            addCriterion("Is_Default not in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_Default between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_Default not between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsEndIsNull() {
            addCriterion("Is_End is null");
            return (Criteria) this;
        }

        public Criteria andIsEndIsNotNull() {
            addCriterion("Is_End is not null");
            return (Criteria) this;
        }

        public Criteria andIsEndEqualTo(Boolean value) {
            addCriterion("Is_End =", value, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndNotEqualTo(Boolean value) {
            addCriterion("Is_End <>", value, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndGreaterThan(Boolean value) {
            addCriterion("Is_End >", value, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndGreaterThanOrEqualTo(Boolean value) {
            addCriterion("Is_End >=", value, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndLessThan(Boolean value) {
            addCriterion("Is_End <", value, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndLessThanOrEqualTo(Boolean value) {
            addCriterion("Is_End <=", value, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndIn(List<Boolean> values) {
            addCriterion("Is_End in", values, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndNotIn(List<Boolean> values) {
            addCriterion("Is_End not in", values, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_End between", value1, value2, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsEndNotBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_End not between", value1, value2, "isEnd");
            return (Criteria) this;
        }

        public Criteria andIsUserfulIsNull() {
            addCriterion("Is_Userful is null");
            return (Criteria) this;
        }

        public Criteria andIsUserfulIsNotNull() {
            addCriterion("Is_Userful is not null");
            return (Criteria) this;
        }

        public Criteria andIsUserfulEqualTo(Boolean value) {
            addCriterion("Is_Userful =", value, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulNotEqualTo(Boolean value) {
            addCriterion("Is_Userful <>", value, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulGreaterThan(Boolean value) {
            addCriterion("Is_Userful >", value, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulGreaterThanOrEqualTo(Boolean value) {
            addCriterion("Is_Userful >=", value, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulLessThan(Boolean value) {
            addCriterion("Is_Userful <", value, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulLessThanOrEqualTo(Boolean value) {
            addCriterion("Is_Userful <=", value, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulIn(List<Boolean> values) {
            addCriterion("Is_Userful in", values, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulNotIn(List<Boolean> values) {
            addCriterion("Is_Userful not in", values, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_Userful between", value1, value2, "isUserful");
            return (Criteria) this;
        }

        public Criteria andIsUserfulNotBetween(Boolean value1, Boolean value2) {
            addCriterion("Is_Userful not between", value1, value2, "isUserful");
            return (Criteria) this;
        }

        public Criteria andStageIsNull() {
            addCriterion("stage is null");
            return (Criteria) this;
        }

        public Criteria andStageIsNotNull() {
            addCriterion("stage is not null");
            return (Criteria) this;
        }

        public Criteria andStageEqualTo(Integer value) {
            addCriterion("stage =", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotEqualTo(Integer value) {
            addCriterion("stage <>", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThan(Integer value) {
            addCriterion("stage >", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThanOrEqualTo(Integer value) {
            addCriterion("stage >=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThan(Integer value) {
            addCriterion("stage <", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThanOrEqualTo(Integer value) {
            addCriterion("stage <=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageIn(List<Integer> values) {
            addCriterion("stage in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotIn(List<Integer> values) {
            addCriterion("stage not in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageBetween(Integer value1, Integer value2) {
            addCriterion("stage between", value1, value2, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotBetween(Integer value1, Integer value2) {
            addCriterion("stage not between", value1, value2, "stage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Project
     *
     * @mbg.generated do_not_delete_during_merge 2020-01-16 18:43:07
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Project
     *
     * @mbg.generated 2020-01-16 18:43:07
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}