package com.mutiny.demo.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Role
 *
 * @mbg.generated do_not_delete_during_merge 2020-01-29 12:48:37
 */
public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Role_ID
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.User_ID
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Role_Name
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   ROLE_ROOT 管理员
     *   ROLE_GOVER 政府
     *   ROLE_ADMIN 企业管理员
     *   ROLE_USER 企业用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Role_Type
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Create_Time
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   该角色的描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Description
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private String description;

    /**
     * Database Column Remarks:
     *   是否有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Is_Userful
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private Boolean isUserful;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Role
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.Role_ID
     *
     * @return the value of Role.Role_ID
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.Role_ID
     *
     * @param roleId the value for Role.Role_ID
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.User_ID
     *
     * @return the value of Role.User_ID
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.User_ID
     *
     * @param userId the value for Role.User_ID
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.Role_Name
     *
     * @return the value of Role.Role_Name
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.Role_Name
     *
     * @param roleName the value for Role.Role_Name
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.Role_Type
     *
     * @return the value of Role.Role_Type
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.Role_Type
     *
     * @param roleType the value for Role.Role_Type
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.Create_Time
     *
     * @return the value of Role.Create_Time
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.Create_Time
     *
     * @param createTime the value for Role.Create_Time
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.Description
     *
     * @return the value of Role.Description
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.Description
     *
     * @param description the value for Role.Description
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.Is_Userful
     *
     * @return the value of Role.Is_Userful
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public Boolean getIsUserful() {
        return isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.Is_Userful
     *
     * @param isUserful the value for Role.Is_Userful
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    public void setIsUserful(Boolean isUserful) {
        this.isUserful = isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbg.generated 2020-01-29 12:48:37
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", userId=").append(userId);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleType=").append(roleType);
        sb.append(", createTime=").append(createTime);
        sb.append(", description=").append(description);
        sb.append(", isUserful=").append(isUserful);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}